### ISSUE TITLE
PDF Export: Bold/Italic text breaks to a new line

### ISSUE THREAD

**Issue by baranka144** [Gram-ax/gramax#267]
### Describe the bug

If a piece of formatted text (like bold or italic) is placed inline with regular text, the PDF export process moves the formatted text to its own line. This splits the original line of text, with the formatted portion appearing between the two parts of the regular text.

This behavior is a side effect of adding support for inline images to the PDF export functionality.

<img width="612" height="782" alt="Image" src="https://github.com/user-attachments/assets/6df6b9cc-729a-42ef-86be-7fdc74a744df" />

**Comment by VasiliyGrigorev** [comment]
fixed

**Comment by kudryashovda** [comment]
2025.7.18-linux.100

the bug is still present

<img width="569" height="429" alt="Image" src="https://github.com/user-attachments/assets/41301e76-c09f-45ee-9fc3-ae706addc46a" />

**Comment by VasiliyGrigorev** [comment]
@kudryashovda please check if this bug is still playing?

**Comment by kudryashovda** [comment]
Version 2025.8.14-linux.138

<img width="848" height="634" alt="Image" src="https://github.com/user-attachments/assets/0f38824f-958f-4913-b2ac-d339e50ea859" />

Yes, it works! Thanks!

PS. text highlighting export is not correct

**Comment by VasiliyGrigorev** [comment]
Exporting text highlights is not supported at the moment. We are working on an update to the export system, after which exporting highlights and other currently unsupported elements will be available.
